import os
import pickle
from langchain.tools import BaseTool
import pandas as pd
from config.root_base import *  # Ensure paths are correctly defined in your config


class AgriculturalDisasterReportTool(BaseTool):
    name: str = "agricultural_disaster_report_tool"
    description: str = (
        "Useful to generate an agricultural disaster report by analyzing all agricultural data using LLM and "
        "combining it with a template."
    )

    def _run(self):
        return mainAgriculturalDisasterReport()

    def _arun(self):
        raise NotImplementedError("agricultural_disaster_report_tool does not support async")


def mainAgriculturalDisasterReport():
    data_analysis = analyze_data()

    report_content = generate_report(data_analysis)

    save_report(report_content)
    return f"Agricultural disaster report has successfully generated and the content is {report_content}."


def analyze_data():
    print('Analyse the agricultural disaster data')
    print('------------------')

    # Example analysis data, which can be expanded with actual data loading logic.
    analyzed_data = {
        'severe_damage_areas': ['Region X', 'Region Y'],
        'total_damage_cost': 5000000,
        'affected_population': 20000,
        'repair_plan_summary': 'Priority to restore irrigation systems and provide seeds in Region X and Y.'
    }
    return analyzed_data


def generate_report(analyzed_data):
    print('Generate the agricultural disaster report')
    print('------------------')

    # Template for agricultural disaster report
    template = """
        Agricultural Disaster Report
        ============================

        1. Affected Areas:
           - {severe_damage_areas}

        2. Total Estimated Damage Cost: ${total_damage_cost}

        3. Affected Population: {affected_population} people

        4. Repair Plan Summary:
           {repair_plan_summary}

        Report generated by LLM.
        """

    # Filling the template with the analyzed data
    report_content = template.format(
        severe_damage_areas=', '.join(analyzed_data['severe_damage_areas']),
        total_damage_cost=analyzed_data['total_damage_cost'],
        affected_population=analyzed_data['affected_population'],
        repair_plan_summary=analyzed_data['repair_plan_summary']
    )

    return report_content


def save_report(report_content):
    print('Store the agricultural disaster report')
    print('------------------')

    disaster_name = 'Lekima'  # Example disaster name (can be dynamically assigned)
    report_file_path = f"{rural_report_root}/{disaster_name}_rural.txt"
    os.makedirs(os.path.dirname(report_file_path), exist_ok=True)

    # Saving the report content to a file
    with open(report_file_path, 'w') as report_file:
        report_file.write(report_content)


if __name__ == "__main__":
    tool = AgriculturalDisasterReportTool()
    res = tool._run()
    print(res)
