import os
import pickle

from langchain.tools import BaseTool
import pandas as pd
from config.root_base import *

class HydrologicalDisasterReportTool(BaseTool):
    name: str = "hydrological_disaster_report_tool"
    description: str = ("Useful to generate a hydrological disaster report by analyzing all hydrological data using "
                        "LLM and combining it with a template.")

    def _run(self):
        return mainHydrologicalDisasterReport()

    def _arun(self):
        raise NotImplementedError("hydrological_disaster_report_tool does not support async")
def mainHydrologicalDisasterReport():
    data_analysis = analyze_data()

    report_content = generate_report(data_analysis)

    save_report(report_content)
    return f"Hydrological disaster report has successfully generated and the content is {report_content}."
def analyze_data():
    print('analyse the hydrological disaster data')
    print('------------------')
    analyzed_data = {
        'severe_damage_areas': ['Region A', 'Region B'],
        'total_damage_cost': 2500000,
        'affected_population': 15000,
        'repair_plan_summary': 'Priority to restore dam and canal systems in Region A and B.'
    }
    return analyzed_data


def generate_report(analyzed_data):
    print('generate the hydrological disaster report')
    print('------------------')
    template = """
        Hydrological Disaster Report
        ============================

        1. Affected Areas:
           - {severe_damage_areas}

        2. Total Estimated Damage Cost: ${total_damage_cost}

        3. Affected Population: {affected_population} people

        4. Repair Plan Summary:
           {repair_plan_summary}

        Report generated by LLM.
        """

    report_content = template.format(
        severe_damage_areas=', '.join(analyzed_data['severe_damage_areas']),
        total_damage_cost=analyzed_data['total_damage_cost'],
        affected_population=analyzed_data['affected_population'],
        repair_plan_summary=analyzed_data['repair_plan_summary']
    )

    return report_content


def save_report(report_content):
    print('store the hydrological disaster report')
    print('------------------')

    disaster_name = 'Lekima'
    # with open(SYSTEM_FILE_PATH, 'rb') as f:
    #     system_memory = pickle.load(f)
    # try:
    #     disaster_name = system_memory['disaster_name']
    # except:
    #     disaster_name = 'unknown'
    report_file_path = f"{hydrological_report_root}/{disaster_name}_hydro.txt"
    os.makedirs(os.path.dirname(report_file_path), exist_ok=True)
    with open(report_file_path, 'w') as report_file:
        report_file.write(report_content)

if __name__ == "__main__":
    tool = HydrologicalDisasterReportTool()
    res = tool._run()
    # print(res)